# +----------------+
# + Version 33.2.0 +
# +----------------+
[buildPlans.OtoshiMono]
family = "Otoshi Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.OtoshiMono.variants.design]
one = "base-long-top-serif"
two = "straight-neck-serifless"
four = "open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "crossing-asymmetric"
nine = "open-contour"
capital-r = "curly-serifless"
f = "flat-hook-serifless"
t = "bent-hook-short-neck2"
asterisk = "hex-high"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-neq = "more-slanted"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.OtoshiMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.OtoshiMono.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.OtoshiMono.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.OtoshiMono.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.OtoshiMono.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.OtoshiMono.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.OtoshiMono.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.OtoshiTerm]
family = "Otoshi Term"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.OtoshiTerm.variants.design]
one = "base-long-top-serif"
two = "straight-neck-serifless"
four = "open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "crossing-asymmetric"
nine = "open-contour"
capital-r = "curly-serifless"
f = "flat-hook-serifless"
t = "bent-hook-short-neck2"
asterisk = "hex-high"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-neq = "more-slanted"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.OtoshiTerm.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.OtoshiTerm.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.OtoshiTerm.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.OtoshiTerm.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.OtoshiTerm.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.OtoshiTerm.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.OtoshiTerm.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"
